### GET USER BY ID TEST
GET http://localhost:8080/users/1
Accept: application/json

###

### POST USER TEST
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "Дамир",
  "surname": "Гарифуллин",
  "patronymic": "Фаилевич",
  "email": "damirgarifullin7@gmail.com",
  "password": "password"
}

### GET ALL USERS TEST
GET http://localhost:8080/users/
Accept: application/json



