version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Business
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gamification-service:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/Business
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    expose:
      - 8080
    ports:
      - "8080:8080"