### ADD PARTICIPANT
POST http://localhost:8080/events/assign
Content-Type: application/json

{
  "user_id": 2,
  "event_id": 1
}

### POST EVENT TEST
POST http://localhost:8080/events/
Content-Type: application/json

{
  "title": "название",
  "description": "описание",
  "type": "Лекция",
  "start_time": "2024-02-23T13:00:00",
  "end_time": "2024-02-23T15:00:00",
  "quote": 10,
  "clan_only": false,
  "authors": [
    2, 6
  ]
}

### GET ALL EVENTS TEST
GET http://localhost:8080/events
Accept: application/json

###
